"""add user ownership to analyses

Revision ID: 6c8175b07b35
Revises: 18a6f8c8b7ff
Create Date: 2026-09-08 13:17:04.385922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8175b07b35'
down_revision: Union[str, Sequence[str], None] = '18a6f8c8b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_column('analyses', 'user_id')
    # ### end Alembic commands ###
