"""add audit metadata to analyses

Revision ID: 775948476015
Revises: bfe12ef74aad
Create Date: 2026-09-06 11:28:19.396706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775948476015'
down_revision: Union[str, Sequence[str], None] = 'bfe12ef74aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'analyses',
    sa.Column(
        'policy_version',
        sa.String(length=20),
        nullable=False,
        server_default='1.0',
        )
    )

    op.add_column(
        'analyses',
        sa.Column(
            'detector_version',
            sa.String(length=20),
            nullable=False,
            server_default='1.0',
        )
    )

    op.add_column(
        'analyses',
        sa.Column(
            'semantic_model',
            sa.String(length=100),
            nullable=False,
            server_default='all-MiniLM-L6-v2',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'semantic_model')
    op.drop_column('analyses', 'detector_version')
    op.drop_column('analyses', 'policy_version')
    # ### end Alembic commands ###
