from enum import Enum


class RiskCategory(str, Enum):
    DESTRUCTIVE = "DESTRUCTIVE"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    CREDENTIAL_ACCESS = "CREDENTIAL_ACCESS"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    PRODUCTION = "PRODUCTION"

    CUSTOMER_DATA = "CUSTOMER_DATA"
    FINANCIAL_DATA = "FINANCIAL_DATA"
    EMPLOYEE_DATA = "EMPLOYEE_DATA"
    DATABASE = "DATABASE"
    TEMPORARY_FILES = "TEMPORARY_FILES"