from app.core.risk_types import RiskCategory


CUSTOMER_DATA_SCORE = 0.15
FINANCIAL_DATA_SCORE = 0.20
EMPLOYEE_DATA_SCORE = 0.10
DATABASE_SCORE = 0.15
TEMPORARY_FILES_SCORE = 0.00


SCOPE_SCORES = {
    RiskCategory.CUSTOMER_DATA: CUSTOMER_DATA_SCORE,
    RiskCategory.FINANCIAL_DATA: FINANCIAL_DATA_SCORE,
    RiskCategory.EMPLOYEE_DATA: EMPLOYEE_DATA_SCORE,
    RiskCategory.DATABASE: DATABASE_SCORE,
    RiskCategory.TEMPORARY_FILES: TEMPORARY_FILES_SCORE,
}